# superuser permission to execute build
sudo: required
services:
  - docker

before_install:
  - docker build -t enricapq/docker-react -f Dockerfile.dev .

script:
  - docker run enricapq/docker-react npm run test -- --coverage